# Generated by Django 2.1.7 on 2019-02-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComicItem',
            new_name='Comic',
        ),
        migrations.RenameModel(
            old_name='EventItem',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='SeriesItem',
            new_name='Series',
        ),
        migrations.RenameModel(
            old_name='StoryItem',
            new_name='Story',
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'series'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'stories'},
        ),
    ]
