# Generated by Django 2.1.7 on 2019-02-16 00:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_storyitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventItem',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('resource_uri', models.URLField(blank=True, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='comics_resource_uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='events_resource_uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='series',
            field=models.ManyToManyField(related_name='series', to='characters.SeriesItem'),
        ),
        migrations.AddField(
            model_name='character',
            name='series_resource_uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='stories',
            field=models.ManyToManyField(related_name='stories', to='characters.StoryItem'),
        ),
        migrations.AddField(
            model_name='character',
            name='stories_resource_uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='events',
            field=models.ManyToManyField(related_name='events', to='characters.EventItem'),
        ),
    ]
