# Generated by Django 2.1.7 on 2019-02-16 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_auto_20190216_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='comics_resource_uri',
        ),
        migrations.RemoveField(
            model_name='character',
            name='events_resource_uri',
        ),
        migrations.RemoveField(
            model_name='character',
            name='series_resource_uri',
        ),
        migrations.RemoveField(
            model_name='character',
            name='stories_resource_uri',
        ),
    ]
