# Generated by Django 2.1.7 on 2019-02-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_auto_20190216_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='comics',
            field=models.ManyToManyField(blank=True, related_name='comics', to='characters.ComicItem'),
        ),
        migrations.AlterField(
            model_name='character',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='events', to='characters.EventItem'),
        ),
        migrations.AlterField(
            model_name='character',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='series', to='characters.SeriesItem'),
        ),
        migrations.AlterField(
            model_name='character',
            name='stories',
            field=models.ManyToManyField(blank=True, related_name='stories', to='characters.StoryItem'),
        ),
    ]
