# Generated by Django 2.1.7 on 2019-02-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_auto_20190216_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='comics',
            field=models.ManyToManyField(blank=True, related_name='characters', to='characters.ComicItem'),
        ),
        migrations.AlterField(
            model_name='character',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='characters', to='characters.EventItem'),
        ),
        migrations.AlterField(
            model_name='character',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='characters', to='characters.SeriesItem'),
        ),
        migrations.AlterField(
            model_name='character',
            name='stories',
            field=models.ManyToManyField(blank=True, related_name='characters', to='characters.StoryItem'),
        ),
    ]
